name: download_task
description: Resumable http download request - pause, resume, cancel, realtime progress and error handling
repository: https://github.com/starkdmi/resumable_download
version: 1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4 # newer versions require at least dart 2.18